### Retrieving data from Yahoo!Finance

1. Go to http://finance.yahoo.com/.
2. Enter IBM in the search box.
3. Click on Historical Price in the middle.
4. Choose the monthly data, then click Apply.
5. Click Download data under Apply.

In [ ]:
#usual imports 

import pandas as pd

In [ ]:
df = pd.read_csv("IBM.csv")

In [ ]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2020-02-01,144.250000,158.750000,126.360001,130.149994,123.664551,118150200
1,2020-03-01,130.750000,136.100006,90.559998,110.930000,106.502930,190076300
2,2020-04-01,106.360001,129.309998,104.519997,125.559998,120.549057,130697400
3,2020-05-01,123.190002,126.970001,111.809998,124.900002,119.915405,92885900
4,2020-06-01,124.639999,135.880005,115.879997,120.769997,117.505257,120996800

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
8,2020-10-01,122.360001,135.500000,105.919998,111.660004,110.064018,159117500
9,2020-11-01,112.650002,125.309998,111.160004,123.519997,121.754494,103669300
10,2020-12-01,123.900002,127.690002,121.720001,125.879997,125.879997,102829600
11,2021-01-01,125.849998,131.880005,123.040001,129.210007,129.210007,37784300
12,2021-01-13,129.149994,129.750000,128.110001,128.125000,128.125000,582903

### Alternative in getting IBM data

In [ ]:
pip install pandas-datareader

Collecting pandas-datareader
  Downloading pandas_datareader-0.9.0-py3-none-any.whl (107 kB)
     |████████████████████████████████| 107 kB 4.7 MB/s eta 0:00:01
Requirement already satisfied: lxml in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from pandas-datareader) (4.5.0)
Requirement already satisfied: requests>=2.19.0 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from pandas-datareader) (2.21.0)
Requirement already satisfied: pandas>=0.23 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from pandas-datareader) (1.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.19.0->pandas-datareader) (2019.11.28)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.19.0->pandas-datareader) (1.24.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.19.0->pandas-datareader) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.19.0->pandas-datareader) (2.8)
Requirement already satisfied: pytz>=2017.3 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from pandas>=0.23->pandas-datareader) (2019.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from pandas>=0.23->pandas-datareader) (2.8.1)
Requirement already satisfied: numpy>=1.16.5 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from pandas>=0.23->pandas-datareader) (1.18.1)
Requirement already satisfied: six>=1.5 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas-datareader) (1.12.0)
Installing collected packages: pandas-datareader
Successfully installed pandas-datareader-0.9.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
pip uninstall pandas-datareader

Found existing installation: pandas-datareader 0.9.0
Uninstalling pandas-datareader-0.9.0:
  Would remove:
    /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages/pandas_datareader-0.9.0.dist-info/*
    /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages/pandas_datareader/*
Proceed (y/n)? ^C
ERROR: Operation cancelled by user
Note: you may need to restart the kernel to use updated packages.

In [ ]:
y

NameError: name 'y' is not defined

In [ ]:
import pandas_datareader.data as getData

df1 = getData.get_data_yahoo("IBM")

In [ ]:
df1.tail()

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2021-01-07,130.460007,128.259995,130.039993,128.990005,4507400.0,128.990005
2021-01-08,129.320007,126.980003,128.570007,128.529999,4676200.0,128.529999
2021-01-11,129.679993,127.660004,127.949997,128.580002,5602500.0,128.580002
2021-01-12,129.850006,127.940002,129.089996,129.210007,3747700.0,129.210007
2021-01-13,129.750000,127.519997,129.149994,127.820000,1303452.0,127.820000

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
8,2020-10-01,122.360001,135.500000,105.919998,111.660004,110.064018,159117500
9,2020-11-01,112.650002,125.309998,111.160004,123.519997,121.754494,103669300
10,2020-12-01,123.900002,127.690002,121.720001,125.879997,125.879997,102829600
11,2021-01-01,125.849998,131.880005,123.040001,129.210007,129.210007,37784300
12,2021-01-13,129.149994,129.750000,128.110001,128.125000,128.125000,582903

We can see there are some differences in the data using the two methods

### Getting a longer time period using datetime

In [ ]:
import pandas_datareader.data as getData
import datetime

In [ ]:
begdate = datetime.datetime(2000,11,1)
enddate= datetime.datetime(2021,10,1)

In [ ]:
df2 = getData.get_data_yahoo("IBM",begdate, enddate)

In [ ]:
df2.head()

                High       Low      Open     Close     Volume  Adj Close
Date
2000-11-01   99.8750   97.2500   98.4375   98.5625  7466200.0  62.973667
2000-11-02  102.3125   98.5000   99.0000  101.9375  7445100.0  65.130013
2000-11-03  102.6250   99.3750  102.5000  100.1250  5848500.0  63.971943
2000-11-06  102.3750   99.4375   99.8750  100.3125  4448500.0  64.091782
2000-11-07  103.5000  100.6875  101.1250  102.3125  5420600.0  65.369598

A careful reader should find that the order of data is different. When downloading data manually, the order is from the latest (such as yesterday) going back in history. However, when retrieving data via a function, we would have the oldest date first. Most financial databases adopt the same sorting order: from the oldest to the latest.

In [ ]:
pip install yfinance

Requirement already satisfied: yfinance in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (0.1.55)
Requirement already satisfied: multitasking>=0.0.7 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (0.0.9)
Requirement already satisfied: lxml>=4.5.1 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (4.6.2)
Requirement already satisfied: numpy>=1.15 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (1.18.1)
Requirement already satisfied: requests>=2.20 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (2.21.0)
Requirement already satisfied: pandas>=0.24 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (1.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (1.24.3)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (2.8)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from pandas>=0.24->yfinance) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from pandas>=0.24->yfinance) (2019.3)
Requirement already satisfied: six>=1.5 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance) (1.12.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
pip install finplot

Collecting finplot
  Downloading finplot-1.5.4-py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 6.0 MB/s eta 0:00:011
Requirement already satisfied: pandas in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from finplot) (1.2.0)
Collecting PyQt5
  Downloading PyQt5-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-macosx_10_13_intel.whl (47.6 MB)
     |████████████████████████████████| 47.6 MB 55.2 MB/s eta 0:00:01
Collecting pyqtgraph>=0.11.1
  Downloading pyqtgraph-0.11.1-py2.py3-none-any.whl (824 kB)
     |████████████████████████████████| 824 kB 36.1 MB/s eta 0:00:01
Requirement already satisfied: numpy>=1.16.5 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from pandas->finplot) (1.18.1)
Requirement already satisfied: pytz>=2017.3 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from pandas->finplot) (2019.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from pandas->finplot) (2.8.1)
Collecting PyQt5-sip<13,>=12.8
  Downloading PyQt5_sip-12.8.1-cp37-cp37m-macosx_10_9_x86_64.whl (63 kB)
     |████████████████████████████████| 63 kB 6.5 MB/s  eta 0:00:01
Requirement already satisfied: six>=1.5 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas->finplot) (1.12.0)
ERROR: spyder 4.0.1 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
ERROR: spyder 4.0.1 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.15.2 which is incompatible.
Installing collected packages: PyQt5-sip, PyQt5, pyqtgraph, finplot
Successfully installed PyQt5-5.15.2 PyQt5-sip-12.8.1 finplot-1.5.4 pyqtgraph-0.11.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import yfinance as yf
import finplot as fplt

df = yf.download('SPY',start='2018-01-01', end = '2020-04-29')
fplt.candlestick_ochl(df[['Open','Close','High','Low']])
fplt.plot(df.Close.rolling(50).mean())
fplt.plot(df.Close.rolling(200).mean())
fplt.show()

[*********************100%***********************]  1 of 1 completed

In [ ]:
pip install --upgrade mplfinance

Collecting mplfinance
  Downloading mplfinance-0.12.7a4-py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 6.6 MB/s eta 0:00:011
Requirement already satisfied, skipping upgrade: matplotlib in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from mplfinance) (3.2.1)
Requirement already satisfied, skipping upgrade: pandas in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from mplfinance) (1.2.0)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from matplotlib->mplfinance) (2.4.6)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from matplotlib->mplfinance) (0.10.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from matplotlib->mplfinance) (2.8.1)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from matplotlib->mplfinance) (1.1.0)
Requirement already satisfied, skipping upgrade: numpy>=1.11 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from matplotlib->mplfinance) (1.18.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.3 in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from pandas->mplfinance) (2019.3)
Requirement already satisfied, skipping upgrade: six in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from cycler>=0.10->matplotlib->mplfinance) (1.12.0)
Requirement already satisfied, skipping upgrade: setuptools in /Users/dark_prince/opt/anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->mplfinance) (46.0.0.post20200309)
Installing collected packages: mplfinance
Successfully installed mplfinance-0.12.7a4
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter, WeekdayLocator
from matplotlib.dates import HourLocator,DayLocator, MONDAY
from matplotlib.finance import candlestick_ohlc,plot_day_summary_oclh
from matplotlib.finance import quotes_historical_yahoo_ochl as getData

ModuleNotFoundError: No module named 'matplotlib.finance'